import './globals.css'
import { Source_Sans_Pro } from 'next/font/google'

const inter = Source_Sans_Pro({ weight: ['400', '700'], subsets: ['vietnamese'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
